# update_fastlane
clear_derived_data

fastlane_version "1.36.3"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods

    # increment_build_number
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    gym(scheme: "PraisePop", workspace: "PraisePop.xcworkspace")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    sigh
    gym(scheme: "PraisePop", workspace: "PraisePop.xcworkspace")
    sh "deliver download_screenshots"
    sh "deliver --submit_for_review"
  end

  after_all do |lane|
    slack(
      message: "Successfully deployed new update for PraisePop!"
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
